version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aldo-shoes
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - database
      - inventory_service

  db:
    image: postgres:15.2
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
    container_name: aldo-shoes-database
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - database

  inventory:
    image: ruby:alpine3.17
    restart: always
    container_name: inventory_service
    working_dir: /inventory_service
    command: /bin/sh -c "apk update && apk add websocketd && websocketd --port=8080 ruby ./inventory.rb"
    volumes:
      - ./inventory_service:/inventory_service
    ports:
      - 8080:8080
    depends_on:
      - web
    networks:
      - inventory_service

volumes:
  database:

networks:
  database:
  inventory_service:
