default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["ALDO_SHOES_DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aldo_shoes_development

test:
  <<: *default
  database: aldo_shoes_test

production:
  <<: *default
  database: aldos_shoes
