# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Aldo Shoes CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    env:
      RAILS_ENV: test
      ALDO_SHOES_DATABASE_URL: "postgres://postgres:postgres@localhost:5432/"
    steps:
      - uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1

      - name: Install gems
        run: bundle lock --add-platform x86_64-linux && bundle install
  
      - name: Set up database schema
        run: bin/rails db:setup

      - name: Run tests
        run: bundle exec rspec
